### ISSUE TITLE
BHoM_UI: Duplication of name in drop-down

### ISSUE THREAD

**Issue by LivAndersson** [BHoM/BHoM_UI#102]
As of discussion with Arnaud, might not be the intention to have the word "Material" appearing twice as separate drop-downs.

![image](https://user-images.githubusercontent.com/42963262/60194372-197db900-9831-11e9-8aa9-ee7386cb6b43.png)

**Comment by LivAndersson** [comment]
Not a duplication, but perhaps related to the subject: is there a need to say both Revit and RevitAdapter? 

![image](https://user-images.githubusercontent.com/42963262/60195430-f6ec9f80-9832-11e9-97de-e015a4053d8d.png)

**Comment by adecler** [comment]
Will now be handled in #136
