### ISSUE TITLE
BHoM_UI: add keyboard control to GlobalSearch

### ISSUE THREAD

**Issue by awakeman** [BHoM/BHoM_UI#105]
Just a thought from some of my use of GlobalSearch recently, it is summoned with the keyboard, the keyboard is used to search but then you have to select with the mouse which is jarring and doesn't feel great from a UX perspective.

Should be simple to add some keybindings to move up and down in the list and select.

Suggested behaviour:

`Up`/`Down` - highlight a result in the list
`Enter` - Select highlighted result
`Esc` - Cancel (close the window)

Top result should be highlighted automatically.

**Comment by rwemay** [comment]
Agree with this - I actually have typed arrow buttons to try and navigate already!

**Comment by awakeman** [comment]
Me too
