### ISSUE TITLE
BHoM_UI is not compiling after latest pull

### ISSUE THREAD

**Issue by AlaaAlfakara** [BHoM/BHoM_UI#108]
Error is : 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "call "C:\GitHub_BHoM\BHoM_UI\Build\UI_PostBuild.exe" ..\..\ "C:\Users\aalfakar\AppData\Roaming\BHoM\Assemblies"" exited with code -532462766.	BHoM_UI			

The only way for me to get it to build is to delete all folders in my assembly folder.

**Comment by epignatelli** [comment]
Have you got Excel, Dynamo, Revit, Grasshopper or Rhino open?

**Comment by AlaaAlfakara** [comment]
@epignatelli  Nope. I checked with task manager to make sure none in open.

**Comment by AlaaAlfakara** [comment]
It turned out to be CodeAssistant Error. It is Building the repos for some reason in the Assembly folder and in the CodeAssistant Repo.
