### ISSUE TITLE
BHoM_UI: Allow 'run periodic' or similar continuous updates in the UI's

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_UI#11]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
Isn't that what the timer in Grasshopper does already?

**Comment by adecler** [comment]
Closing as now replaced by the new `SolutionExpired` event in BHoM_UI Caller
