### ISSUE TITLE
If only one method for a type make the type clickable together with the method

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_UI#123]

**Comment by adecler** [comment]
@eduardo, I believe this is covered by #136 now. IF true, can you close this?

**Comment by epignatelli** [comment]
This was actually something different. If there is only one leaf in a branch of the menu, the branch entry of the menu should be clickable as well.
Although, if we are removing that layer completely because of #136, this is superseeded.
Closing it, in case the idea of implementing it comes back, we can reopen.
