### ISSUE TITLE
BHoM_UI: Add ability to add hyperlink to Wiki in menu

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#13]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
Considering this solved by the new entry on the local menu `Source code`. 
If not, @al-fisher I can reopen this!
