### ISSUE TITLE
Refer to consistently named "Datasets" folders across all repos and AppData folder

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#132]
Following close out of https://github.com/BHoM/BHoM_UI/pull/131

Ensure consistency of `Datasets` naming convention:

 - [ ]  Update `targetDatasetsFolder` to refer to `"Datasets"` not `"DataSets"` 
 - [ ]  Update `sourceFolder` to copy from `"Datasets"` not `"DataSets"`

**Comment by adecler** [comment]
Not relevant anymore now that we are not using UI_PostBuild.
@al-fisher , correct me if I missunderstood.
