### ISSUE TITLE
BHoM_UI: Added clarity of when component become obsolete

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#139]
#### Description:
When a BHoM method is updated it currently (in Grasshopper atleast) becomes yellow and claims to be old or becomes yellow and asks you to right-click to select method. 

This works well in smaller scrips, but I at least often have bigger scripts where a lot of the components are both yellow and red when working as intended. This causes a problem where when you are returning to a script you can find that it is no longer working, and currently there isn't any easy way to see what changed. This is much worse when the component that became obsolete doesn't "break" the script noticeably but changes the output. 

The latter one is the main problem that I would like to avoid. 

Can't say I'm sure of exactly how but preferably something that will let you know that something changed because of an BHoM update and perhaps something that shows where in the document the changed was
(Grasshopper has a find tool [F3] to search among the component names in the document, might be helpful if we can only show the names of updated components)

**Comment by adecler** [comment]
Need to be reviewed in light of versioning

**Comment by al-fisher** [comment]
@kThorsager when you get a moment 😄 - very much worth you adding some new updated comments below on this issue based on your latest experience and also, as @adecler says, with new versioning functionality. 
Thanks 👍

**Comment by kThorsager** [comment]
I would say that Versioning does reduce the number of times that this could be an issue, which is great.
The issue that if components stop working it will be hard to understand it however, is still present.

i.e. I forgot to properly build a part of the BHoM or a part of the BHoM was removed.
I've seen a mix of the red `method is not implemented` or yellow `This is a magic component`.
Which can be hard to decipher in hindsight as often you're using methods in ways where they're yellow (or red) when it's working.

Something like:
![image](https://user-images.githubusercontent.com/53530468/79318718-3fc72f00-7eff-11ea-921c-9d419ee87b12.png)
Would be nice, but they don't appear in this way as they are not GH components.

So essentially I would like to be able to open a GH script (or any UI) and know if any of the methods which I was using, is no longer working without opening every warning message

**Comment by FraserGreenroyd** [comment]
In light of versioning existing now for several years, I feel this issue has diminished from @kThorsager original observations, with the issues now relating to developer error when building code locally rather than opening scripts for project use, so I'm closing this issue on that basis.
