### ISSUE TITLE
BHoM_UI: Update method list menus and de-serialisation of component

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#140]
#### Description:

To be able to execute code compiled at run time two things need to be added to the BHoM UI:

1. Ability to re-trigger the menu generation in the UI based on an updated BHoMMethodList or similar.
2. Re de-serialisation of any component in whichever UI environment that is currently running to get any part of a script previously generated to work.

**Comment by adecler** [comment]
Closing as this is a feature that isn't in the roadmap anymore
