### ISSUE TITLE
BHoM_UI: setting a empty list from a C# component in SetProperty

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#141]
#### Description:
To remove openings from a panel I'm setting a empty Openings list `List<Openings>` with `SetProperty` in Grasshopper. This used to work but now i first throws the error: `GetDataList() can only be called on a parameter with access set to GH_ParamAccess.list`

Thus I change it to List access, where it throws this error: `
Unable to cast object of type 'System.Collections.Generic.List`1[BH.oM.Structure.Elements.Opening]' to type 'BH.oM.Structure.Elements.Opening'.`

Then I change it back to Item access where it works...
and then I exit my cluster and it's broken again

I tried this outside of an cluster as well and it broke upon reopening the document.

It can also be "fixed" by re-attaching any of the Input wires, but updating the data in the objects did not.

Duplicating the Component re-broke it again

#### Test file(s):
[TestFile](https://burohappold.sharepoint.com/:u:/s/BHoM/EVQVAm4UWcROi0HRY9YQgmkBxaSxVLqXoeM70t_K4rPQyA?e=aGOs9e)

**Comment by adecler** [comment]
Let's have our cake and eat it: 
- Create the `ClearProperty` method
- See if we can call it from @kThorsager user's case when that problem is triggered.
- Provide a default null value for the `SetProperty` component so that people can easily set a property to null (or empty list)
