### ISSUE TITLE
BHoM_UI: Backwards compatibility of Explode component

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#142]
#### Description:

When opening an older script with an explode component in it, if the object has changed in any way, the explode component stops working. All outputs are returning null

#### How to replicate:

Open an old script with an explode component in it where the object itself has changed in terms of properties

#### Expected behaviour:

The unchanged properties named the same way should still give correct outputs instead of null. Warning message should still appear, telling the user that they probably need to update. 

Long term once versioning engine is implemented this could potentially be used to re-map properties, but think that is a separate issue.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_UI/BHoM_UI-Issue142-BackwardsCompatibilityOfExplode?csf=1&e=8ylsSd

**Comment by adecler** [comment]
@IsakNaslundBh ,

This is what I get when I try your script:

![image](https://user-images.githubusercontent.com/16853390/72039006-682b0600-32de-11ea-8af0-486fb298196c.png)

After clicking on `Update Outputs` in the context menu of the first explode, I get this:

![image](https://user-images.githubusercontent.com/16853390/72039094-bcce8100-32de-11ea-9890-030914137899.png)

I am aware that there are a few weird behaviours with the explode component that need fixing but this example seems to be working fine for me. Do you mind testing it again on your side?
