### ISSUE TITLE
Explode method performance improvements

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_UI#153]
#### Description:

The explode component is quite slow, testing a Grasshopper script just now, is around 10x slower than the upstream component performing translations on 3.5k IFramingElement objects. As chatted with @adecler just now, we think this is reflection rather than preview (preview turned off didn't have a significant effect), so potentially some performance improvements in pre-compiling when outputs are refreshed.

**Comment by epignatelli** [comment]
How slow is it? I tested with 5000 `Beam`s and it takes around 700ms.
![image](https://user-images.githubusercontent.com/26899347/68287930-7446dd00-007b-11ea-8dbd-778db7c453d0.png)

**Comment by rwemay** [comment]
Thanks @epignatelli , similar performance to me - 500-600ms for 3.5k versus 35-50ms for the upstream translation component. I know not necessarily comparing apples with apples on explode versus translate, but definitely feels more lag than I think it should/could. @adecler seemed confident it could be improved. I raised it as we use things like Explode and GetProperty (similar performance) a LOT so does tend to slow scripts.

**Comment by epignatelli** [comment]
Ok, no problem!! I just wanted to make sure I got the issue!

**Comment by adecler** [comment]
I believe this was solved a few years ago. Feel free to reopen if I am mistakem
