### ISSUE TITLE
Tags cannot be provided as input in the CreateObject 

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_UI#154]
#### Description:

When using the `CreateObject` component, if you check the `Tags` input, the component crashes.

#### How to replicate:

1. Checkout this branch https://github.com/BHoM/BHoM_UI/pull/152 and compile the code accordingly
1. Open Grasshopper
1. Create a `CreateObject` component
1. Select the `oM.Structure.Elements.Bar` constructor by object initializer
1. Right click, check `Tags` properties.

#### Expected behaviour:

We can either find a way to input tags, or remove them at all. I lean towards the second one.

**Comment by adecler** [comment]
The solution is to provide a converter from List to HashSet I think

**Comment by adecler** [comment]
We should also take care of fragment set

**Comment by pawelbaran** [comment]
@adecler this started becoming an issue as the autoinitializers of types having properties of type `HashSet<>` fail and cannot be used. Therefore, could we please prioritize this to make sure it will be resolved in the current Milestone?

Below a solution I have patched up yesterday - it can definitely be neater + it requires .NET Framework 4.7.2 (`ToHashSet` method has been introduced then). Dropping it here for reference, you should know better whether it is the way to go.

        protected virtual Func<DataAccessor, object> CreateInputAccessor(Type dataType, int index)
        {
            UnderlyingType subType = dataType.UnderlyingType();
            string methodName = (subType.Depth == 0) ? "GetDataItem" : (subType.Depth == 1) ? "GetDataList" : "GetDataTree";

            MethodInfo method = DataAccessor.GetType().GetMethod(methodName).MakeGenericMethod(subType.Type);

            ParameterExpression lambdaInput1 = Expression.Parameter(typeof(DataAccessor), "accessor");
            ParameterExpression[] lambdaInputs = new ParameterExpression[] { lambdaInput1 };

            Expression[] methodInputs = new Expression[] { Expression.Constant(index) };
            MethodCallExpression methodExpression = Expression.Call(Expression.Convert(lambdaInput1, DataAccessor.GetType()), method, methodInputs);
            Func<DataAccessor, object> lambda = Expression.Lambda<Func<DataAccessor, object>>(Expression.Convert(methodExpression, typeof(object)), lambdaInputs).Compile();

            bool isArray = dataType.IsArray;
            bool isHashSet = dataType.IsGenericType && typeof(HashSet<>) == dataType.GetGenericTypeDefinition();
            if (!isArray && !isHashSet)
                return lambda;
            
            MethodInfo castMethod;
            if (isArray)
                castMethod = typeof(Enumerable).GetMethod("ToArray").MakeGenericMethod(subType.Type);
            else
            {
                MethodInfo mi = typeof(Enumerable).GetMethods().Where(x=>x.Name== "ToHashSet").First();
                castMethod = mi.MakeGenericMethod(subType.Type);
            }
            ParameterExpression lambdaResult = Expression.Parameter(typeof(object), "lambdaResult");
            MethodCallExpression castExpression = Expression.Call(null, castMethod, Expression.Convert(lambdaResult, typeof(IEnumerable<>).MakeGenericType(subType.Type)));
            Func<object, object> castDelegate = Expression.Lambda<Func<object, object>>(castExpression, lambdaResult).Compile();

            return (accessor) => { return castDelegate(lambda(accessor)); };
        }

@al-fisher FYI following today's call

**Comment by adecler** [comment]
Right, I am off today and tomorrow so the earliest I can look at this is Saturday. 
May I however remind you that issues raised during one sprint should not be pushed for that same sprint. Even more so when there is only two days left.

**Comment by pawelbaran** [comment]
No worries, I meant _Milestone_, not _Sprint - just would be good to have it covered before the next Beta.

**Comment by adecler** [comment]
> I meant Milestone, not _Sprint

It's actually my bad. I re-read you comment and you said 'milestone'. My apologies, I shouldn't answer comments just before a meeting.

Yes, this is definitely coming this quarter. Most likely next sprint actually.
