### ISSUE TITLE
CreateObject component: The Add/Remove Inputs menu closes after checking one item

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_UI#157]
#### Description:

At the moment, the menu closes when the user checks or unchecks one of its entries. When dealing with long list of inputs (e.g. `Bar`) it is useful to keep the menu open, and let it close only when we click outside of it.
![AutoCloseOff](https://user-images.githubusercontent.com/26899347/68381654-1cc37280-014a-11ea-86a0-88db7ce55f9a.gif)

**Comment by adecler** [comment]
Fixed
