### ISSUE TITLE
Copy-Paste BHoM objects between software

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_UI#158]
#### Description:

Maybe a ridiculous idea, but was just thinking would be good to copy/paste objects between Grasshopper/Dynamo/Excel. Presumably could just call a context menu, or ctrl-C/ctrl-V to copy a collection from Grasshopper to a List in Excel or collection in Dynamo and then carry on using the objects.

**Comment by adecler** [comment]
I would push further (but not for this issue/PR): Copy-Paste of scripts between software (this should be possible with the node2code toolkit)

**Comment by adecler** [comment]
By the way, you currently have two ways I can think of to do what you are asking for:
- Use sockets
- Convert to Json and copy-paste that

**Comment by rwemay** [comment]
Thanks! Yes have been using sockets mainly to date. I see this as a potential positive side effect of something else rather than a specific functionality to build. 

One workflow I can see it being very useful for is testing - copy pasting objects created between different software's to quickly test something (whether for code building or projects).

**Comment by adecler** [comment]
Closing as this has not been requested for over three year. Will re-open if this becomes relevant for exiting user cases.
