### ISSUE TITLE
Add support for Description Attribute on enums in UI

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#169]
The code supports `[Description("...")]` on `enums` - we need to add exposure to the UIs

**Comment by rwemay** [comment]
@al-fisher , @adecler , not sure if this is in the scope of this issue, but as chatted to @ChrisShrub it would be good if we could automatically reflect enum options into input help text/attributes. There should be a limit on these where the inputs go over say 10(?). This would then allow anyone to see what options there are for enum inputs for a _lot_ of cases where there are a handful of options. A string-enum lookup in BHoM_UI can then deal with finding the enum (apologies, not sure if this is implemented already, I normally use the actual enum).

**Comment by al-fisher** [comment]
Good idea - this could be similar to how we are handling tooltips for Interfaces - listing objects that implement that interface truncating and appending with _"... and more"_ when list is too long

**Comment by IsakNaslundBh** [comment]
Closed by https://github.com/BHoM/BHoM_UI/pull/221/files
