### ISSUE TITLE
BHoM_UI: Remove boilerplate text for errors?

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#179]
Currently when an error is raised somewhere in the process and returned to the user, the UI adds the text "1. This component failed to run properly. Are you sure you have the correct type of inputs?
Check their description for more details. Here is the error provided by the method:" before the actual message is received. I personally feel this is more in the way for reading the actual error message and not that helpful. Also not sure if it helps new-starters as it generally will not be able to give any guidance of what is wrong. I would vote for removing this text and only returning the error message from the method. Would be glad for inputs from others here as well @FraserGreenroyd @adecler @al-fisher @alelom @epignatelli @JosefTaylor @enarhi @peterjamesnugent 

![image](https://user-images.githubusercontent.com/22005920/71825960-27907a00-309d-11ea-8458-55e2ecb0622e.png)

**Comment by FraserGreenroyd** [comment]
I would vote for removing it as well. I know it's confused some people on my end in the past, and I've got distracted by it at the beginning as well! Definitely a thumbs up on removal from me.

**Comment by rwemay** [comment]
I think a good idea. Good to get any feedback/comments on the intention of the text in the first place? (was it just a first pass/to be helpful or is there a wider reason for inclusion that we're missing). @adecler , @al-fisher ?

**Comment by epignatelli** [comment]
I partly agree with this.
I think it is useful for debugging purposes, and to have more control, to understand if the error happened either when: collecting the data, computing the reflected method or when outputting the result. 

But I agree that the message is currently unecessarily verbose.

Maybe we can add our own BHoM `Exception` and make the `Computer.Record*` methods include some info about the exception (as @alelom suggested in another occasion).

**Comment by alelom** [comment]
I agree on the unnecessary verbosity that should be removed. But that to me is mostly a cosmetic issue. 
Real trouble I see in how we handle the exceptions (especially for new starters) is that we often oversimplify the message ending up returning a potentially confusing message.

> Maybe we can add our own BHoM `Exception` and make the `Compute.Record*` methods include some info about the exception (as @alelom suggested in another occasion).

Here the question I raised on that:
https://github.com/BHoM/BHoM_Engine/issues/1375

there's also a proposal implementation there.

We could tackle these two things together.

**Comment by alelom** [comment]
Also, I would not underestimate the importance of a reminder such as "_Are you sure you have the correct type of inputs?_", especially if the alternative is to leave the user with `Object not set to an instance of an object`. I'd be careful in removing that part.

**Comment by al-fisher** [comment]
One thing I would recommend is reversing the order of the messages. 
i.e. you get the _Specific Error Provided by the Method_ **_First_** and then a shorter general comment like "_Are you sure you have the correct type of inputs?_"

**Comment by adecler** [comment]
The problem with the "_Are you sure you have the correct inputs?_" message is that it is triggered only when an exception was thrown and not caught until the top level `Run` method in the UI. Modifying the `Compute.Record` method doesn't help since it is never actually called until we reach the `Run` method. Say we do that change as suggested, here's what we will get:

![image](https://user-images.githubusercontent.com/16853390/71944204-0abf8800-31fe-11ea-9afa-9016294f9d7a.png)

I think we can all agree this is actually making it worst.

There is a call stack record inside the caught exception itself though. So, using Alessio's idea of only showing the first two items of the stack that are within BH code, we can get something like this:

![image](https://user-images.githubusercontent.com/16853390/71945883-034ead80-3203-11ea-9868-fb0b328cbe87.png)


```c#
try
{
    result = Run(inputs);
}
catch (Exception e)
{
    string message = "This component failed to run properly. Are you sure you have the correct type of inputs?\n" +
                        "Check their description for more details. Here is the error provided by the method:\n   ";

    if (e.InnerException != null)
        message += e.InnerException.Message;
    else
        message += e.Message;

    List<string> stack = e.StackTrace.Split(new char[] { '\n' })
        .Where(x => x.Contains(" BH."))
        .Take(2)
        .ToList();

    if (stack.Count > 0)
        message += "\nHappened " + stack[0].Trim();
    if (stack.Count > 1)
        message += "\n   called " + stack[1].Trim();

    Engine.Reflection.Compute.RecordError(message);

    return false;
}
```

What do you think?

**Comment by al-fisher** [comment]
I like this - going to be very useful! 
I might suggest some formatting changes to make more readable still as is a lot of info ... propose going from most specific to generic in terms of information to the user.

Something like

“Error: “ 
+ InnerExceptionMessage 
+ “\n Error occurred in “ + stack[0] 
+ “ called from “ + stack[1] 
+ “\n Are you sure you have the correct type of inputs?”

What do you think?

**Comment by adecler** [comment]
Based on @al-fisher comment, here's the new version:

![image](https://user-images.githubusercontent.com/16853390/72030616-8dab1600-32c4-11ea-8c67-99ceb84d4d6e.png)
