### ISSUE TITLE
BHoM_UI: Ability to open the code from any function in The Engine

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_UI#188]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by al-fisher** [comment]
Yes - above sounds good. 

We already have `BH.Engine.Reflection.Query.Url` for both `MethodBase` and `Type`

However I also wonder if we can/will need to include a some form of compliance check. From looking at this before I think some methods/parts of the code mapped better to their url than others. 
Be good to ensure clear rules / guidelines so we do not have lots of exceptions.

We are probably looking much better as a result of the compliance checks already in place - but nice to be explicit - i.e. additional check `IsValidUrl` on `BH.Engine.Reflection.Query.Url(MethodBase/Type)` across all toolkits
