### ISSUE TITLE
External namespace omitted in context menus

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_UI#192]
#### Describe the documentation issue:
It looks as though the BH.oM.External namespace is omitting the external in the context menu - hence a lot of adapter/external software showing up at the same level as discipline toolkits etc.

**Comment by al-fisher** [comment]
Just raised an issue [here](https://github.com/BHoM/BHoM_Adapter/issues/210) on ensuring Adapter namespaces are all compliant.

Thus good to confirm the _External_ at least are being populated correctly in UI. From my brief testing just know - @rwemay's query above still seems to be occurring

**Comment by adecler** [comment]
Now resolved in issues mentioned above
