### ISSUE TITLE
BHoM_UI: Explode gives script variable for similar but not same type

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#197]
#### Description:

When inputting for example a wall and a floor explode, all the outputs become ScriptVariable rather than their exact type, even though they share an identical interface. This makes the geometry not visible etc. Everything is still outputted correctly from the component though, just the GH type is wrong.

#### How to replicate:

plug a list of mixed types that share an interface into the explode.

#### Expected behaviour:

FOr the type assignements to be correct (for example geometry outputs to be Geoemtry Paramas)

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EpaxJufb1DdPiIi93ktlfrcBcHulKYoF3cilK-9dKo1JdA?e=DLdAvW

**Comment by epignatelli** [comment]
I think the main issue here was raised a while ago in the engine, about finding the closest commonf parent type between two objects. Maybe for display purposes we could just check if they are `BHoMObject`s?

**Comment by adecler** [comment]
@epignatelli , In the example from Isak, the property has the same name and same type so it is likely just a problem of the way objects are first grouped by type before handling their properties. I'll fix this once the BHoM_Ui repo is unlocked from existing PRs
