### ISSUE TITLE
Allow to return `null` from a Push

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_UI#202]
#### Description:

![image](https://user-images.githubusercontent.com/6352844/74025438-dd503080-499b-11ea-9ae1-db353037d22d.png)

**Comment by adecler** [comment]
Fixed in https://github.com/BHoM/BHoM_UI/pull/329.
More specifically by commit https://github.com/BHoM/BHoM_UI/commit/a68eb3d6486742ae8dc09a3a4d5b12443f82faa0
