### ISSUE TITLE
BHoM_UI: Explode of fragments

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#203]
#### Description:

Currently the explode does not let you see the content of the fragments. Would need to update the explode to either add fragments as output when a object is exploded or have a specialcase on the explode for the `FragmentSet` giving all of the fragments it consists of:

![image](https://user-images.githubusercontent.com/22005920/74035641-ec92a680-49ba-11ea-9467-d4866b577a67.png)

**Comment by adecler** [comment]
Yes, I think FragmentSet should be turned into a list straight away before being outputted to the UI.

**Comment by IsakNaslundBh** [comment]
> Yes, I think FragmentSet should be turned into a list straight away before being outputted to the UI.

Either that or treat it as a dictionary that you can explode (as we do with custom data)

**Comment by adecler** [comment]
> Either that or treat it as a dictionary that you can explode (as we do with custom data)

Maybe ? The dictionary can only be exploded if the keys are strings so we would use the name of the types ? It seems a bit dangerous unless we use the full type name (i.e. with namespace) and that is pretty messy as output name on a component.

**Comment by IsakNaslundBh** [comment]
> Maybe ? The dictionary can only be exploded if the keys are strings so we would use the name of the types ? It seems a bit dangerous unless we use the full type name (i.e. with namespace) and that is pretty messy as output name on a component.

Yes, was thinking of using types names, but guess I did not fully think it through, that you ofc will need full type names for this to work safely. Then, agreed, think a simple list is fine!

**Comment by adecler** [comment]
Quoting @IsakNaslundBh 

> Also love that fragments now work in the explode! 👍 

source: https://github.com/BHoM/BHoM_UI/pull/253#pullrequestreview-406665005
