### ISSUE TITLE
BHoM_UI: Handling of default values for auto-constructor

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#205]
As we move more and more to the auto-generated property assignment creates, some things have come to mind that these methods right now wont be able to handle:

- Required properties for the object to be valid (Start and End node for a bar for example)
- Kind of related, but warnings for properties that you generally will want to assign for certain workflows to work (names for properties that are to be pushed to a structural package for example)

There are also some cases where we want to pull default values from some Dataset or similar if no property is provided (this ofc already sits under the valid Create method context, but might be a simple property assignment method, that just checks for default values if nothing is provided and raises a note/warning that this has been done).

Some solutions that come to mind, also from some initial discussion with @al-fisher , is to solve this by some attributes that can be added to the oM. For Required properties we could simply add a `Required` attribute that you could put on properties, and then the auto create component could basically just treat these inputs as non-optional.

For warnings, we could have a similar attribute warning, something like `DefaultValueWarning` attribute that could be used as
`[DefaultValueWarning("The name of the section has not been set. Please be aware that you will need to set the name of this object to be able to push it to most structural packages!")]`

For the case of required/default values, it will be trickier when the required proeprty comes from the base BHoMObject, but that could be solved by making all properties on the BHoMObject virtual (think we almost should do this anyway in the spirit of "everything should be hackable") and then simply overriding them and adding the attributes when needed.

Just some general thought. I know more warnings and instructions as to what is required/needed for certain workflows to work has been requested by several users, and just want to make sure the autocreates does not move us one step away from that. Thankful for any comments/other ideas.

@al-fisher @adecler @rwemay @FraserGreenroyd @alelom @epignatelli @JosefTaylor @peterjamesnugent

**Comment by FraserGreenroyd** [comment]
@tg359 tagging you in on this as well.

This is something I've discussed with @tg359 as well, as there are a few instances where we want create methods which basically mirror the auto-create methods, but contain additional checks and warnings to the user if they're not plugging in the right inputs.

I would almost suggest an attribute of `[DoNotAutoCreate]` could be used on objects where specific creates are needed but avoid duplicating creates (i.e. avoid having two creates with the same inputs but one offers protection checks and the other doesn't) might be helpful?

**Comment by adecler** [comment]
Related to https://github.com/BHoM/BHoM/issues/731
