### ISSUE TITLE
BHoM_UI: Disconnects for edge cases of Versioning_Toolkit

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#214]
#### Description:

any component which the outputs name has been changed since its creation and after which is upgraded by the Versioning_Toolkit gets its output disconnected

#### Steps to reproduce:

1. Create a component
2. Change the output's name in the code with a Reflection Attribute
3. Save the script again, (changing the output does not update the component in the script but still works fine)
4. Have that component be upgraded by the Versioning_Toolkit
5. The output disconnects from whatever it was attached to.

#### Test file(s):

After the migration of `IElement`
https://burohappold.sharepoint.com/:u:/s/BHoM/EVxEhCrhhWJOgo6GIht_7X4Buo0roQUlk-4pF6xEefIkew?e=rlPVIf

**Comment by kThorsager** [comment]
On a planning call this has been identified as important, is there an update on this? @adecler

**Comment by adecler** [comment]
@kThorsager , UI has been on the back-burner for a while to prioritise other framework aspects like versioning and serialisation so, no, no update. I'll assign the issue to myself and will try to get it done this sprint.

**Comment by adecler** [comment]
When you provide a large test file, please also provide some details on where the bug is. From your initial comment, I was expecting the `IElement` output to fail but that works for me. Nothing else appear as clearly related to the bug as there are missing components in this script anyway. 

![image](https://user-images.githubusercontent.com/16853390/79826847-5d006f80-83cf-11ea-88aa-0a9a89dfd9a2.png)

**Comment by kThorsager** [comment]
Sorry, I had forgotten that I linked that file here, (and also foolishly didn't copy it to a dedicated place). 
And as it was part of a larger collection of test-scripts it got caught when I updated them

**Comment by adecler** [comment]
@kThorsager , I had to revert the fix done in PR #244  as it was causing important issues with the adapter methods (see https://github.com/BHoM/Versioning_Toolkit/pull/70#pullrequestreview-399946551).

So I am reopening this and will have to find a better way to fix this issue. Can you provide the test file that reproduces the problem raised here ?
