### ISSUE TITLE
BHoM_UI: tags and local settings

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_UI#215]
#### Description:

Following the discussion with @al-fisher and @kThorsager, I am writing down the ideas for UI improvements that we came up with:
- Method tags, possibly really helpful to identify methods that are e.g. related to a certain workflow. These could be divided into:
    - Default tags - either hard coded in the source or stored in a local file
    - Custom tags - to be stored locally in _%appdata%_

    Plus @al-fisher's idea: a ❤️ button to mark favourite methods
- A window with data tree, where the user could check/uncheck each assembly/method to include or remove it from the search (better UX plus faster search?)

To be compared against #85

Suggestions and thoughts are welcome!

**Comment by pawelbaran** [comment]
Is that something we would like to resurrect @FraserGreenroyd?

**Comment by FraserGreenroyd** [comment]
I think so, I've been discussing similar with @travispotterBH recently on similar things - so yeah let's keep this one open and assign it to me, I'll tackle it in a milestone or so.

**Comment by al-fisher** [comment]
Great - thanks both - I agree worth relooking at and prioritising if we can - as anything that can improve the discoverability of most useful methods in the code for different users will be massive

**Comment by pawelbaran** [comment]
Yeah - I would support it even more now when the Revit UI starts getting crowdy very quickly 👍

**Comment by FraserGreenroyd** [comment]
See [this branch](https://github.com/BHoM/BHoM_UI/tree/BHoM_UI-%23215-Settings) for initial work.
