### ISSUE TITLE
BHoM_UI: Handle deprecated methods

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_UI#22]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
@adecler is this still relevant? I couldn't find more info in the issue archive.

**Comment by epignatelli** [comment]
Closing this as I deprecated methods are handled, by removing them from the menu. Further implementations are UI specific, e.g. old label on components.
@ZiolkowskiJakub @awakeman FYI

https://github.com/BHoM/BHoM_UI/issues/81 is still an issue and has to be solved separately.
