### ISSUE TITLE
BHoM_UI: External subnamespace is explicitly culled out from method tree for components

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#223]
#### Issue

Thanks to the introduction to the `External` component, an exception for this word in the method tree was added to the Organise method for menu for all engine components.

https://github.com/BHoM/BHoM_UI/blob/3ba297b14facb1c851b4582f55a205380c3c9511/UI_Engine/Compute/Organise.cs#L59-L73

For https://github.com/BHoM/BHoM_Adapter/issues/213 it is critical that this does not happen, as it would mean no effect in the UI, which is one of the main reason that is actioned.

We hence need to remove the "External" word from the `toSkip` list.

@epignatelli would you be able to check what this does to the External component, making sure it still runs as expected, or if we need to add some exception to the rule here?

@al-fisher @adecler @FraserGreenroyd @alelom

**Comment by alelom** [comment]
This explains https://github.com/BHoM/BHoM_UI/issues/192

**Comment by IsakNaslundBh** [comment]
> This explains #192 ?

yep. Anything in the `toSkip` text will be culled out.

**Comment by alelom** [comment]
Then this is definitely to be resolved in order to allow https://github.com/BHoM/BHoM_Adapter/issues/210 too.

**Comment by alelom** [comment]
@epignatelli do you think you could solve this within this sprint? We'd need this to be solved to move onto the External renaming.

**Comment by epignatelli** [comment]
Hitting on it right now - I'll get back to you asap

**Comment by epignatelli** [comment]
Hi guys, I just pull requested the change [here](https://github.com/BHoM/BHoM_UI/pull/246) and [here](https://github.com/BHoM/Grasshopper_Toolkit/pull/499).

Let me know if this works from the Adapter side of things

**Comment by adecler** [comment]
Now resolved in issues mentioned above

**Comment by adecler** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge
