### ISSUE TITLE
Move logic of "default" Requests from the UI Pull component to the Adapter Pull method

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_UI#228]
### Description:

The piece of code that determines what the Pull will do when a `null` or empty Request is specified is currently residing in the UI:

https://github.com/BHoM/BHoM_UI/blob/c0bab976c356f775bcaf49ae75e4ad526dab7e9b/BHoM_UI/Components/Adapter/Pull.cs#L107-L117

however there are different cases where this behaviour may or may not be desirable.

For example, in [Revit we want to avoid "pulling everything" if the Request input is `null`](https://github.com/BHoM/Revit_Toolkit/issues/611), a condition currently ensured by the first if case. This because you might be inadvertently trigger the Pull with a request that became invalid from an old script (`null`ed) and potentially have to wait a long time if a large model is pulled.

On the other hand, in Socket_Toolkit you want this behaviour to be the default: users should not need to construct a specific request in order to "Pull everything".

This points to the need of moving that logic inside the base Pull action in the BHoM_Adapter, so the behaviour can be controlled by individual toolkits.

[The part of the code that deals with a default ActionConfig being instantiated](https://github.com/BHoM/BHoM_UI/blob/c0bab976c356f775bcaf49ae75e4ad526dab7e9b/BHoM_UI/Components/Adapter/Pull.cs#L97-L105) can remain in the UI component, because this way we can ensure that it is always present no matter if the AdapterActions are overridden or not.

#### Distributed issue
Once the code is moved, this requires to check if all existing overrides of the Pull method are working: create distributed issue.

**Comment by adecler** [comment]
This would be great. The same should be done for all code inside the other adapter components too as those checks/pre-processing should be the responsibility of the adapter, not the UI.

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/BHoM_Adapter/pull/264
