### ISSUE TITLE
Add ability to buffer data outputted from Pull component

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_UI#236]
#### Description:
Will probably need to be turned on/off as a global setting dependant on the max size of the buffered data (before the component stops buffering)

**Comment by al-fisher** [comment]
To include in this functionality also the ability to have periodic and asynchronous pull.
This will require the state of the outputed data to be communicated on the component.
i.e. `Up to date`, `Pulling...`,  `New Data Available` .etc.

To manage this status potential to use the Hash as a comparison between the Hash of the Pulled Data and the Outputted. To see if changed and notify.

Can also plan for the to be based on a Diffing Config also - such that ultimately we can control the flow of information through our Pull based on Tolerances etc.

**Comment by al-fisher** [comment]
This whole feature is a subject of our 4.0 milestone workshops - so further clarity and actions to be recorded then also.

**Comment by adecler** [comment]
The Pull is actually already keeping it's data when it is turned off (`active` input set to `false`). This was done during the UI refactoring. I believe this is sufficient since we can internalise if we need more than that. Correct me if I am wrong.

As for the asynchronous pull, I think this is a completely different issue. So either we repurpose this one or we create another one but he work required is very different so unlikely to be done at the same time (if there is still something to do on the buffering of the pull).

Finally, I'd rather focus this quarter on making sure that the existing functionality and code structure are refined and bug free instead of adding new functionality. Especially since asynchronous functionality is another can of worms with a ton of potential bugs.
