### ISSUE TITLE
BHoM_UI: Adapter icon is identical to BHoMObject

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#237]
#### Description:

Need to be updated to contain an A next to the box.

@adecler to dig out source files for current params.

**Comment by adecler** [comment]
Icons can be found in https://github.com/BHoM/BHoM_UI/tree/master/BHoM_UI/Properties/Resources

**Comment by michaelhoehn** [comment]
Just created a PR within the Grasshopper_Toolkit repo to knock this out. I wasn't sure if this needed to be addressed in the BHoM_UI or could be handled within the GH tk since the primitives are GH specific. Happy to move things where needed 😄  

https://github.com/BHoM/Grasshopper_Toolkit/pull/520

**Comment by adecler** [comment]
Solved by https://github.com/BHoM/Grasshopper_Toolkit/pull/520
