### ISSUE TITLE
Explode component to handle Explosion of collections with sub-collections

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_UI#241]
### Test script
https://burohappold.sharepoint.com/:f:/s/BHoM/EjVMJJUBEGBFs8wPbN3zm5gBLntrzwVfVU6JA-MJmF9gbA?e=GbahsF

#### Issue description:

I am confused at the behaviour of the Explode component for this case:
![image](https://user-images.githubusercontent.com/6352844/79239858-f5936e80-7e68-11ea-887d-bf574232fc5e.png)

It seems like it doesn't manage to populate the outputs correctly.
I tried to follow through the code in the UI, I could not spot where things go wrong.

To show that the values are actually there, I casted the Dictionary to its same type:
![image](https://user-images.githubusercontent.com/6352844/79246578-46a76080-7e71-11ea-9720-957c72f28abb.png)

#### Desired behaviour
Explode outputs should be correctly populated, i.e. in the first image `StartNode.Position.X` should contain a tuple that can be further exploded like in the second image.

**Comment by adecler** [comment]
The issue that you have here is that you are using dictionary keys with `.` in them. That is overlapping with a feature that allows you to access a property of a property:

![image](https://user-images.githubusercontent.com/16853390/79300268-d05e3900-7f18-11ea-8427-bd766cd116a0.png)

**Comment by alelom** [comment]
As agreed during the call, replacing this issue with a workaround as described in https://github.com/BHoM/BHoM_Engine/issues/1660
