### ISSUE TITLE
BHoM_UI: Allow SetProperty for Multiple Properties on Single Object

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_UI#250]
#### Description:
Current Process results in multiple iterations of single object.
Would require to cascade setprop after setprop on a single object (not an intuitive process)
![image](https://user-images.githubusercontent.com/34316256/80720953-a20d5b80-8acb-11ea-8e26-2743440c4706.png)

**Comment by adecler** [comment]
> (not an intuitive process)

Isn't that exactly how Grasshopper works though ? For it to work as you expect, we would need a `SetProperties` component that would take a list of `PropertyNames` and a list of `values` as input. I have not issue with that but this is a different component.

**Comment by kayleighhoude** [comment]
Agreed `SetPropertyList` or similar
