### ISSUE TITLE
Throwing System.UnauthorizedAccessException on PostBuild CopyUpgrades

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#251]
I am getting an error from the post build events when building BHoM UI.

`Error		The command "call "C:\BHoMGitHub\BHoM_UI\Build\UI_PostBuild.exe" ..\..\ "C:\Users\afisher\AppData\Roaming\BHoM\Assemblies"" exited with code -532462766.`	

This is failing as part of the `CopyUpgraders` and on investigation is on line 65 when attempting to access a folder which it does not have permissions for.	Specifically a `System.UnathorizedAccessException`

https://github.com/BHoM/BHoM_UI/blob/35fd6b747cea05582d04594e19f44e30e98ce876/UI_PostBuild/CopyUpgrades.cs#L65

As discussed with @IsakNaslundBh a few options to consider here to catch this and make fail safe.

- First would be to have a parent for-loop iterating across each toolkit folder - before calling `Directory.GetFiles`. This would allow as to gracefully catch an exception for individual toolkits/folders - without crashing out entirely and losing abitlity to copy any of the upgraders.

- The second option - which I think might be a preference - and perhaps in addition to option one, is to limit the search to top level of toolkit folders etc. - i.e. not fully recursive. And thus also being more deliberate about aggregating files only from where they should be expected.

Naturally this second option constrains more where upgraders can be stored, to a more defined BHoM standard upgrader compliance - (both good and bad) but will equally reduce risk further of mining unexpected files, access to miscellaneous folders etc. 
As code base continues to grow. No bad thing I think to enforce a relatively low threshold compliance for file locations.

@adecler good to get your thoughts.
Thanks again @IsakNaslundBh
@rolyhudson @kThorsager this was the issue discussed this morning in our stand up FYI

**Comment by adecler** [comment]
> The second option - which I think might be a preference - and perhaps in addition to option one, is to limit the search to top level of toolkit folders etc. - i.e. not fully recursive. And thus also being more deliberate about aggregating files only from where they should be expected.

Yes, that was my initial idea too but it would currently not work with Dynamo_Toolkit folder structure. That being said, that structure is causing problems with the code assistant too so food for thoughts.
