### ISSUE TITLE
Create friendly names for BHoM_UI core methods

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_UI#252]
#### Description:

This arose from Excel_Toolkit where method names were shortened previously. Examples of methods currently exposed in the latest Excel TK PR shown below: 

 - =GetPropertyCaller.Components.GetProperty?by_Object_String()
 - =Modify.Reflection.SetProperty?by_BHoMObject_String_Object()
 - =GetInfoCaller.Components.GetInfo()
 - =Convert.Serialiser.ToJson?by_Object()
 - =Convert.Serialiser.FromJson?by_String()
 - =CreateDictionaryCaller.Components.CreateDictionary?by_ListOfObject_ListOfObject_Type_Type()
 - =Adapter.Move?by_BHoMAdapter_BHoMAdapter_IRequest_PullType_ActionConfig_PushType_ActionConfig_Boolean()
 - =Adapter.Execute?by_BHoMAdapter_IExecuteCommand_ActionConfig_Boolean()
 - =Adapter.Remove?by_BHoMAdapter_IRequest_ActionConfig_Boolean()
 - =Adapter.Pull?by_BHoMAdapter_Object_PullType_ActionConfig_Boolean()
 - =Adapter.Push?by_BHoMAdapter_IEnumerableOfObject_String_PushType_ActionConfig_Boolean()

@kayleighhoude , @al-fisher @IsakNaslundBh FYI

**Comment by rwemay** [comment]
Some suggestions for 'friendly names' below, and very specifically for Excel use case (so feel free to move this to Excel_Toolkit) but thought we could start the convo of dealing with this potentially at the BHoM_UI level. 

- =GetPropertyCaller.Components.GetProperty?by_Object_String()
     - BHoM.Engine.GetProperty()
- =Modify.Reflection.SetProperty?by_BHoMObject_String_Object()
     - BHoM.Engine.SetProperty()
- =GetInfoCaller.Components.GetInfo()
     - BHoM.GetInfo()
- =Convert.Serialiser.ToJson?by_Object()
     - BHoM.Convert.ToJson()
- =Convert.Serialiser.FromJson?by_String()
     - BHoM.Convert.FromJson()
- =CreateDictionaryCaller.Components.CreateDictionary?by_ListOfObject_ListOfObject_Type_Type()
     - BHoM.Create.Dictionary()
- =Adapter.Move?by_BHoMAdapter_BHoMAdapter_IRequest_PullType_ActionConfig_PushType_ActionConfig_Boolean()
     - BHoM.Adapter.Move()
- =Adapter.Execute?by_BHoMAdapter_IExecuteCommand_ActionConfig_Boolean()
     - BHoM.Adapter.Execute()
- =Adapter.Remove?by_BHoMAdapter_IRequest_ActionConfig_Boolean()
     - BHoM.Adapter.Remove()
- =Adapter.Pull?by_BHoMAdapter_Object_PullType_ActionConfig_Boolean()
     - BHoM.Adapter.Pull()
- =Adapter.Push?by_BHoMAdapter_IEnumerableOfObject_String_PushType_ActionConfig_Boolean()
     - BHoM.Adapter.Push()

**Comment by al-fisher** [comment]
Cool - I like this idea - although worth for completeness mapping the methods in the code that these names actually expose also though I think. 
The components are of course in some cases simply exposing a method in a specific namespace more readily. And, for a multitude of reasons, in some cases divert slightly in naming at each level.

In order for a friendly name to be intuitive for all - good to map both ends. 

For instance 
`BH.UI.Components.GetProperty` exposes `BH.Engine.Reflection.Query.PropertyValue(obj, propName)`
`BH.UI.Components.FromJson` exposes `BH.Engine.Serialiser.Convert.FromJson()`

I think a table to clarify all these relationships will be helpful. As the choice of BHoM.Engine or BHoM.Convert or BHoM.Adapter in the friendly name maybe more confusing if inconsistent with the code namespace

**Comment by rwemay** [comment]
Yes, perfect, makes sense (and not sure why I wrote BHoM.XX as opposed to BH.XX!

@adecler what do you think? I can help to implement if necessary as really keen to get Excel sorted.

**Comment by rwemay** [comment]
> I think a table to clarify all these relationships will be helpful. As the choice of BHoM.Engine or BHoM.Convert or BHoM.Adapter in the friendly name maybe more confusing if inconsistent with the code namespace

Sorry... just to confirm was not intending to include BHoM, I updated the suggestion above to BH.XX

**Comment by al-fisher** [comment]
Yep - makes more sense 😄 
Think then we have the three categorises that map to the tabs in Grasshopper too!
For example:

BH.oM.Create.Dictionary()
BH.Engine.FromJson()
BH.Adpater.Move()

**Comment by rwemay** [comment]
Just to highlight also then, the GH global search results would also be slightly more user-friendly (in my opinion anyway!). Not that these are as critical as Excel where the formula are highly visible and interactive. 

![callers](https://user-images.githubusercontent.com/15233608/81088738-51469a00-8ef3-11ea-8f09-71346a929dbc.gif)

**Comment by al-fisher** [comment]
Leveraging the abstract `BH.UI.Templates.Caller` class - if we follow the conversion suggested in my comment above https://github.com/BHoM/BHoM_UI/issues/252#issuecomment-624093233 then we can generate a "friendly name" through concatenation of existing properties.

I might actually then call this `FullName` and can be implemented as a query method.

For example

``` C#
FullName = "BH." + Caller.Category + "." + Caller.Name;

```


This is distinct from the namespace of course and as such will not modify the GH global search shown above @rwemay. 


Should we wish to take this approach we will need to ensure both `Name` and `Category` are overriden for all implementations of the `Caller` class.

@adecler good to get your comment on the above as an approach. Think is simple and will not effect any of the current implementations of the BHoM UIs - but can be leveraged straight away to resolve the issues with Excel.

If agreed on strategy I am happy to help and raise a PR on the UI side?

**Comment by adecler** [comment]
We actually already have this is the BHoM_UI: https://github.com/BHoM/BHoM_UI/blob/cae71919c17b162752e4a9ee840b6306a5490b6c/BHoM_UI/Global/SearchMenu.cs#L117

This hard-code the content since reflection was apparently too slow for it.  Three things to do though
- Refresh the display text for those to match Al's suggestion
- Possibly move them to a separate method to better highlight their existence and improve availability separately from the other search items if needed
- Fix the name of Delete -> Remove

Ironically, Grasshopper contains a complicated mining of the ribbon to add those a second time with a naming convention closer to what Al is suggesting: https://github.com/BHoM/Grasshopper_Toolkit/blob/dc8269388b5a672f49fb56a6cf7056dbfdbe3fa1/Grasshopper_UI/Global/GlobalSearch.cs#L304

This should just be removed I think. If I understood you correctly @rwemay , this will remove the confusion you mentioned in your last comment. 

One think that is probably worth clarifying: Isn't Excel using the `PossibleItems` from the GlobalMenu to create it's list of available methods ? If not, why ?

**Comment by al-fisher** [comment]
Perfect - thanks @adecler 

Above looks good. I think the three highlighted points make sense. Including point two to separate out as discrete method.

> Ironically, Grasshopper contains a complicated mining of the ribbon to add those a second time with a naming convention closer to what Al is suggesting: https://github.com/BHoM/Grasshopper_Toolkit/blob/dc8269388b5a672f49fb56a6cf7056dbfdbe3fa1/Grasshopper_UI/Global/GlobalSearch.cs#L304

 Yep - agree - prob makes sense to make this a priori! 😄
