### ISSUE TITLE
BHoM_UI: Ensure one faulty input does not break the component

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#255]
https://github.com/BHoM/BHoM_UI/blob/b577503790df9777ebcbe41196e2f1a36390762d/BHoM_UI/Templates/Caller.cs#L378-L381

calling `.ToArray()` on `null` throws an exception, which breaks the entire component.

Found while testing where I'm inputting a list of `ICurve`s where only say `Line` is valid for the component.

Currently Inputs up until the error are returned normally and nothing is returned afterwards.

![image](https://user-images.githubusercontent.com/53530468/81273796-561c6280-9047-11ea-9471-cbbf52b0af80.png)

if we switch it to `return null` at `L378` the component returns null for faulty inputs instead of nothing and does not stop following inputs, which are correct, from being executed.

![image](https://user-images.githubusercontent.com/53530468/81273973-94198680-9047-11ea-97b4-e2fa937de4bb.png)

Think this would be a safe and good improvement, but am a bit unaccustomed to the BHoM_UI so wouldn't mind some feedback @adecler @epignatelli

**Comment by adecler** [comment]
See last commit of https://github.com/BHoM/BHoM_UI/pull/253
