### ISSUE TITLE
BHoM_UI: Inconsistencies for usability of objects with explicit casts

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#276]
### The Problem
We recently added explicit casts between some `ICurve`s.

#### 1. Solved case
Which trough the UI means that if someone provides a Line-like `Polyline` to an `Line` input, the UI will cast it to the correct type and everything works.

This does,
- takes a specific type
- casts to a specific type

#### 2. Dispatching through `as dynamic`
Another case is where someone provides the same Line-like Polyline to a interface method expecting an `ICurve`, which will then lead to the `Polyline` being dispatched with `as dynamic` to the correct method.
`as dynamic` will never make use of casting (at least not user defined explicit ones) and if no method has been provided for `Polyline` it will fail.

![image](https://user-images.githubusercontent.com/53530468/83623508-53028c80-a589-11ea-96a5-1d984305e237.png)

So what we'd want here is,
- taking an interface type
- see the available methods
- try to cast to that type

#### 3. Partially defined methods
Another case, which is similar to the last one, is `IElement`s which allows any kind of `ICurve` to be used in its framework but for which many of the methods are only defined for linear ones.
As of now there is no surefire way to do the equivalent of the casting which happens at the UI level in the code, and hence a behaviour which is enabled and encouraged in the UI sets spokes in the wheels in these methods.
i.e. an `IFramingElement` could be defined by a Line-like `Polyline` an receive the error that it's not line based. Which would confuse any user as they immediately could input the geometrical definition of the element into a methods for `Line`s without issue.

![image](https://user-images.githubusercontent.com/53530468/83624668-cf499f80-a58a-11ea-8b0a-5301ffa91c89.png)

So what we'd want here is,
- taking an interface type
- try to cast to a specific type

### Technical things about the casting
the `as` keyword will only do unboxing of types, not casting
C# disallows user defined casts from a interface to a object, i.e. `(Line)AnICuveObject` will not work, (even as unboxing if I remember correctly)
So any use of the explicit casting system in the code would involve:
1. determining the objects type
2. have some list of acceptable casts, (or maintain specific explicit casts to every other type in `ICurve` and similar, or have a try-catch situation)
3. unbox and call the casting.

### Some thoughts on solutions
When i first encountered this issue I was mostly interested in getting a way to go from `ICurve` to `Line` which would use or mirror the casting system.
My thoughts went to the `Convert` methods which would ofc determine the current objects type through `as dynamic`.
But it would essentially be duplicating what's happening in the oM, which isn't that nice or maintainable.

Another thought following that one would be having the UI use the `Convert` methods, which would remove the need for the casts and consolidate the logic, but don't know how feasible that is and it would not solve `2.`

As far as I can tell I'm stumped to say that `2.` is solvable without heavy use of reflection in every interface method, which I'm assuming we'd want to avoid.

Anyway, these are the annoyances that plague me about this and I'm hopeful for better solutions
(also not convinced that BHoM_UI is the perfect place, but it might not be completely wrong?)

**Comment by adecler** [comment]
Now solved: 

![image](https://user-images.githubusercontent.com/16853390/211544008-fd97f639-6508-4929-86d1-e68c810ff80f.png)
