### ISSUE TITLE
BHoM_UI: Can't Ctrl+Z "past" a explode component

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#281]
#### Description:

I placed a explode component on the canvas, then tried to Ctrl+Z to undo it, but the explode component does not disappear and nothing else does either.

#### Steps to reproduce:

Had this setup in Grasshopper, seems to work for any exploded object, but have not tested for other UIs

![image](https://user-images.githubusercontent.com/53530468/85376660-ea775180-b52f-11ea-9078-5d96322e9b4e.png)

**Comment by adecler** [comment]
Thanks @kThorsager . 
Luckily it is only affecting the Explode component itself. Any Ctrl+z after that will still revert the last actions. So I think it is ok to solve it in 3.3

**Comment by adecler** [comment]
This will be fixed once the UI refactoring PR is merged (https://github.com/BHoM/BHoM_UI/pull/297)

![Explode_CtrlZBug](https://user-images.githubusercontent.com/16853390/92301383-02d70400-ef96-11ea-84a8-33e6c0010615.gif)
