### ISSUE TITLE
BHoM_UI : Modification of menu titles for CreateObject for clarity 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#30]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
Closing, since this is now a duplicate of https://github.com/BHoM/BHoM_UI/issues/92
