### ISSUE TITLE
Provide better support for non compliant code (eg. objects with static Properties)

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#307]
#### Description:

On selection of Acoustic Panel Create - the create component fails to initialise correctly

 

#### Steps to reproduce:

![FailingCreateObject](https://user-images.githubusercontent.com/15924573/93459875-4c9ae500-f8da-11ea-8dbd-ce02714051fe.gif)

Another case is the unsuported use of array in the oM. See https://github.com/BHoM/Grasshopper_Toolkit/issues/542.

**Comment by al-fisher** [comment]
On investigation of what is special about the `Acoustic.Panel` noting it has a `static` Property

``` C#
namespace BH.oM.Acoustic
{
    public class Panel : BHoMObject
    {
        /***************************************************/
        /**** Properties                                ****/
        /***************************************************/

        public virtual Mesh Surface { get; set; } = new Mesh();

        public static int PanelID { get; set; } = 0;

        public Dictionary<Frequency, double> R { get; set; } = new Dictionary<Frequency, double>
        {
            { Frequency.Hz63, 1 }, { Frequency.Hz125, 1 }, { Frequency.Hz250, 1 }, { Frequency.Hz500, 1 }, { Frequency.Hz1000, 1 },
            { Frequency.Hz2000, 1 }, { Frequency.Hz4000, 1 }, { Frequency.Hz8000, 1 }, { Frequency.Hz16000, 1 },
        };


        /***************************************************/
    }
```

**Comment by al-fisher** [comment]
On ensuring `PanelID` is `virtual` not `static` - fixes the issue
![image](https://user-images.githubusercontent.com/15924573/93460838-c41d4400-f8db-11ea-8b63-ecba212b1fcd.png)

I will raise an issue in the Acoustic_oM.
@adecler not sure if we what to handle these cases or catch failure in a different way at the UI level - as oM definition is not compliant? 
Therefore not critical either.

**Comment by al-fisher** [comment]
@adecler I have fixed this for this occurrence in https://github.com/BHoM/BHoM/pull/996 and updated the issue title to reflect.
Leave this for you to comment on/action/close if we want more protection or handle failure differently at UI. 
As above not urgent

**Comment by adecler** [comment]
@al-fisher , I'll keep this open since I am getting a decent amount of bug issues raised on the UI that are actually due to people writing non-compliant code. 

So might be a good thing to have the UI better cover for those cases.

**Comment by al-fisher** [comment]
Yes - agreed.
Thanks

**Comment by adecler** [comment]
Not a problem anymore:
![FixedIssue_01](https://user-images.githubusercontent.com/16853390/211551064-332dce39-c239-477c-b255-23594b6cd4e7.gif)
