### ISSUE TITLE
Provide support for out method parameters

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_UI#313]
See discussion in https://github.com/BHoM/BHoM_Engine/issues/2015

In principle, it should be fairly straightforward to implement and would reduce the risk of having to choose between writing a method for the UI of for internal C# use. 

In lots of ways, a similar issue to https://github.com/BHoM/BHoM_UI/issues/268. So should probably do them together.

**Comment by IsakNaslundBh** [comment]
I like this. Would be very neat from the code side!

**Comment by pawelbaran** [comment]
Yeah, I would also be happy with this!

**Comment by adecler** [comment]
parked in branch `BHoM_UI-#313-OutParamSupport` as it is proving more problematic than expected

**Comment by adecler** [comment]
Closing as parked since 2020
