### ISSUE TITLE
New event chain for event raised since last run (and in need to be displayed in the UI)

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_UI#314]

**Comment by adecler** [comment]
@alelom , is it still relevant now that we have the `GetEvents` component ? 
I honestly don't remember exactly what this is about so happy to close if you are too ?

**Comment by alelom** [comment]
I think this was in order to allow "capture" of Warning/Exceptions maybe?

**Comment by adecler** [comment]
Closing this based on discussion with @alelom
