### ISSUE TITLE
Create splash screen on launch of any BHoM UI

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#337]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
From the original issue, given the use of daily alphas and BHoM version components within each UI, is a splash screen still relevant @al-fisher ?

**Comment by al-fisher** [comment]
Yes - probably not - I think appropriate to close this specific issue. With general plans for revamping installers and pop ups superseding  this old issue.

Thanks @FraserGreenroyd
