### ISSUE TITLE
BHoM_UI: Error when re-building exited with code -532462766

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_UI#34]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
Closing since it now builds
