### ISSUE TITLE
BHoM_UI:  showing input variables by variable type and not by name?

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_UI#41]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
From the archive, @adecler 's comment was to add both type and name. 
I would give it a try and check how long the longest methods are. 

Are we still of the same idea?
