### ISSUE TITLE
Clean Up of Titles in Requests and Query

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_UI#415]
#### Description:
Per conversations with @al-fisher, placing this issue under UI (one for next milestone):

![image](https://user-images.githubusercontent.com/34316256/158641539-d6b1c30d-624a-411d-a30b-64b1b2c26711.png)
^Confusing nomenclature when search Query methods (why does this say NonBHoMObjects?)

![image](https://user-images.githubusercontent.com/34316256/158641727-97aad7cf-4979-405f-ba4c-1e8b66235075.png)
^Confusing naming here as well. Searching for something like Type Filter via Ctrl+Shift+B yields many results, I usually direct people to do it the old fashioned way, but the typical requests are under "Data", why is it referred to as Data here?

**Comment by FraserGreenroyd** [comment]
The first issue has been noted by @adecler as being a result of the move to .NetStandard2.0 so will be able to be resolved in 5.2.

The second issue is under `Data` because the namespace for the objects will be `BH.oM.Data.Requests.XYZ`, so that's not something that will be changed in this repository for those objects.

**Comment by FraserGreenroyd** [comment]
@kayleighhoude I ran today's alpha and could not replicate this issue anymore, could you check and confirm if it's still an issue for you? 😄

**Comment by jamesramsden-bh** [comment]
Cannot replicate top image. 
![image](https://user-images.githubusercontent.com/84443868/184644271-b27dcc91-bdb4-43b0-b9e5-a2ae11f7f0f7.png)
Tested on alpha 220812

**Comment by al-fisher** [comment]
Thanks @jamesramsden-bh @FraserGreenroyd
