### ISSUE TITLE
Null exception on LogUsage

### ISSUE THREAD

**Issue by vietle-bh** [BHoM/BHoM_UI#442]
#### Description:

I was pulling Revit grids to Grasshopper when this happened:
![image](https://user-images.githubusercontent.com/102604891/205691889-2366a184-518b-4256-9213-462d02121efb.png)

This doesn't look like an error on the Revit_Toolkit side because the elements did make it into Rhino.
![image](https://user-images.githubusercontent.com/102604891/205693464-6e70cbe4-0acc-4187-8483-f37224f75b6b.png)

This seems like the exception location:
![image](https://user-images.githubusercontent.com/102604891/205692172-f00b0353-71ed-4c99-a672-d801287098c3.png)
![image](https://user-images.githubusercontent.com/102604891/205692044-fe261b3f-ac57-4c6f-97f6-e75f6478c6df.png)

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_UI/%23431-LogUsageNullException?csf=1&web=1&e=IHdJhY)

#### Steps to reproduce:

- Open the RVT file in Revit and activate the adapter
- Open the GH file in Rhino
- Set the Toggle for Pull Grids to True
- Only the first grid will be pulled before the exception shows up in red
![image](https://user-images.githubusercontent.com/102604891/205693035-10757d41-9c28-4d23-88aa-bcbee5207e5f.png)

#### Expected behaviour:

All grids should be pulled without exception.

**Comment by vietle-bh** [comment]
FYI..... @pawelbaran @michal-pekacki  @travispotterBH @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
@vietle-bh can I confirm you were running the latest beta artefact for testing from this morning or an alpha?

**Comment by vietle-bh** [comment]
I think it's the latest ([here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F05%5FCI%20CD%2FBeta%20Artefacts%20for%20testing%2FBuroHappoldEngineering&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&OR=Teams%2DHL&CT=1670258958701)). I then rebuilt repos from their main branches to find the exception point.
