### ISSUE TITLE
bhom

### ISSUE THREAD

**Issue by shashank-poola** [BHoM/BHoM_UI#459]

**Comment by FraserGreenroyd** [comment]
Hi @shashank-poola welcome to BHoM land!

I suspect this might have been an accidental issue given its lack of content, so I'm going to close it for now to avoid it being picked up as something for the team to work on, but if you have any further questions/comments/discussions, I'd recommend taking a look at [our discussions board](https://github.com/orgs/BHoM/discussions) 😄
