### ISSUE TITLE
BHoM_UI Build Issue

### ISSUE THREAD

**Issue by mariatjader** [BHoM/BHoM_UI#62]
Hi all,
Yesterday and today I am getting these errors when trying to build BHoM_UI. The other repo builds are going fine and I have deleted and cloned my repo. Any ideas?
Maria

![image](https://user-images.githubusercontent.com/42934052/51244290-9f413280-197c-11e9-948d-f99803c9f9a5.png)

**Comment by IsakNaslundBh** [comment]
Can you check that you do not have Excel running? Excel_Toolkit is using the dll's in that location, so they can not be modified when it is.

Also to double check this, check in the taskmanager that Excel do not have any process running in the background. Had that problem yesterday.

**Comment by mariatjader** [comment]
Thank you @IsakNaslundBh . I checked now but it does not seem to be any excel processes running. Any other thoughts?

**Comment by mariatjader** [comment]
I experimented a bit with the Post build event, I changed it to be \BHoM and then changed it back to be \BHoM\Assemblies after having deleted that folder once. It seems to work now.
