### ISSUE TITLE
BHoM_UI - Pull query doesn't filter

### ISSUE THREAD

**Issue by arturtomczak** [BHoM/BHoM_UI#70]
Query input to the Pull method doesn't filter the data as expected:
![image](https://user-images.githubusercontent.com/34334902/51923476-5dd46c80-23eb-11e9-97ba-d69f8c429f30.png)
(Post Pull quering works as expected)

**Comment by arturtomczak** [comment]
Sorry for not adding any labels, but this function is disabled on my account.

**Comment by adecler** [comment]
Hi @arturtomczak , thanks for raising the issue. 
The socket adapter doesn't currently provide that functionality so I have labelled this as a feature request. I'll add this when I have time as it creates confusion in this state. In the mean time you can either send different type of objects on different ports or use a dispatch to separate them after the pull.

**Comment by al-fisher** [comment]
> Sorry for not adding any labels, but this function is disabled on my account.

Hey @arturtomczak - I have actually updated the Wiki page on raising issues to clarify 
https://github.com/BHoM/documentation/wiki/Submitting-an-Issue
Hope makes sense. There will be some more material around coding roles and governance appearing shortly too. Do shout again anytime if anything is unclear/unexpected. Cheers

**Comment by adecler** [comment]
I have now raised the issue in the Socket_Toolkit repo: https://github.com/BHoM/Socket_Toolkit/issues/52
