### ISSUE TITLE
BHoM_UI: Set correct output for explode when values of different types are used for the same key

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#72]
When different types are fed in to the same key, the explode component would need to find a common denominator between the values set to the key.

For example, setting different types of geometry to the same key in a custom object.

See test file:

[DifferentTypeCustomData.zip](https://github.com/BHoM/BHoM_UI/files/2816284/DifferentTypeCustomData.zip)

Linked to what @epignatelli started working on here:

https://github.com/BHoM/BHoM_Engine/issues/780

**Comment by adecler** [comment]
@IsakNaslundBh , can you provide a bit more information?

**Comment by IsakNaslundBh** [comment]
Sorry, @adecler . I have updated the description.
