### ISSUE TITLE
BHoM_UI: Speed of explode component

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#73]
The explode component can take quite some time to run when plugging in a fairly big number of objects.

Explding ~18 000 nodes takes around 3 minutes on my machine.

As we will want to be able to use it for results where the quantities can be in the millions, the performance of this component for big sets of data will be important.

**Comment by epignatelli** [comment]
This is a grasshopper issue, moving it to the Grasshopper_Toolkit

**Comment by adecler** [comment]
Should we close this issue then?
