### ISSUE TITLE
BHoM_UI: Missing Input description

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_UI#79]
Input description is missing..

![image](https://user-images.githubusercontent.com/26113670/52284609-a694a400-295c-11e9-8a6e-62b9336c1eef.png)

![image](https://user-images.githubusercontent.com/26113670/52284804-0a1ed180-295d-11e9-823f-92405799fd7a.png)

**Comment by epignatelli** [comment]
The description strategy generally works.
Your `Input` attribute has a typo: `NumberofTimestepsperHour` to `numberOfTimeStepsPerHour`
