### ISSUE TITLE
BHoM_UI: Deprecated query method is showing up in global serach

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#81]
For the global ctrl+b search, query methods modifying a query shows up 

![image](https://user-images.githubusercontent.com/22005920/53254045-dfee4300-36c2-11e9-94dd-72f259711830.png)

The method can not be accessed via the modify component or the createQuery component. Only shows up for the global menu.

**Comment by epignatelli** [comment]
Connected to https://github.com/BHoM/Grasshopper_Toolkit/issues/330, is this caused by the assembly version behind as well?
